apiVersion: apps/v1
kind: Deployment
metadata:
  # name: cvat-nginx
  name: cvat-traefik
  namespace: cvat
  labels:
    app: cvat-app
    tier: proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cvat-app
      tier: proxy
  template:
    metadata:
      labels:
        app: cvat-app
        tier: proxy
    spec:
      containers:
      # - name: nginx
      - name: traefik
        # image: nginx
        image: traefik:v2.4
        ports:
        # - containerPort: 80
        - containerPort: 8080
        volumeMounts:
        # - mountPath: /etc/nginx
        - mountPath: /var/run
          readOnly: true
          name: cvat-nginx-conf
        # - mountPath: /var/log/nginx
        - mountPath: /var/log/traefik
          name: log
      volumes:
      - name: cvat-nginx-conf
        configMap:
          name: cvat-nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
            - key: mime.types
              path: mime.types
            - key: cvat.conf
              path: cvat.d/cvat.conf
      - name: log
        emptyDir: {}
