apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvat-opa
  namespace: cvat
  labels:
    app: cvat-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cvat-app
  template:
    metadata:
      labels:
        app: cvat-app
    spec:
      containers:
      - name: cvat-opa
        image: vishnu00245/opa
        ports:
        - containerPort: 8181         
